// Country data service for GlobeLoom - Enhanced with 30+ countries
import React from "react";

// Comprehensive countries data for the explorer with iconic landmarks
export const countries = [
  {
    id: 1,
    name: "Japan",
    code: "JP",
    flag: "🇯🇵",
    continent: "Asia",
    capital: "Tokyo",
    description:
      "Land of the Rising Sun, where ancient traditions meet cutting-edge technology",
    rating: 4.9,
    visitors: "31.9M",
    bestTime: "Mar-May, Sep-Nov",
    highlights: ["Mount Fuji", "Tokyo", "Kyoto", "Cherry Blossoms"],
    iconicQuery: "Mount Fuji cherry blossoms Japan",
    image:
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "22°C", condition: "Sunny", humidity: "65%" },
    tags: ["Culture", "Technology", "Nature", "Food"],
  },
  {
    id: 2,
    name: "France",
    code: "FR",
    flag: "🇫🇷",
    continent: "Europe",
    capital: "Paris",
    description: "The country of romance, art, and world-renowned cuisine",
    rating: 4.8,
    visitors: "89.4M",
    bestTime: "Apr-Jun, Sep-Nov",
    highlights: ["Eiffel Tower", "Louvre", "Provence", "French Riviera"],
    iconicQuery: "Eiffel Tower Paris France",
    image:
      "https://images.unsplash.com/photo-1502602898536-47ad22581b52?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "18°C", condition: "Partly Cloudy", humidity: "70%" },
    tags: ["Romance", "Art", "Food", "History"],
  },
  {
    id: 3,
    name: "Iceland",
    code: "IS",
    flag: "🇮🇸",
    continent: "Europe",
    capital: "Reykjavik",
    description: "Land of fire and ice with stunning natural phenomena",
    rating: 4.7,
    visitors: "2.3M",
    bestTime: "Jun-Aug, Nov-Mar",
    highlights: ["Northern Lights", "Blue Lagoon", "Geysir", "Waterfalls"],
    iconicQuery: "Blue Lagoon geothermal Iceland",
    image:
      "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "8°C", condition: "Clear", humidity: "75%" },
    tags: ["Nature", "Adventure", "Northern Lights", "Geothermal"],
  },
  {
    id: 4,
    name: "Italy",
    code: "IT",
    flag: "🇮🇹",
    continent: "Europe",
    capital: "Rome",
    description:
      "Home to ancient Rome, Renaissance art, and incredible cuisine",
    rating: 4.8,
    visitors: "65.0M",
    bestTime: "Apr-Jun, Sep-Oct",
    highlights: ["Colosseum", "Venice", "Tuscany", "Vatican City"],
    iconicQuery: "Colosseum Rome Italy",
    image:
      "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "20°C", condition: "Sunny", humidity: "68%" },
    tags: ["History", "Art", "Food", "Architecture"],
  },
  {
    id: 5,
    name: "Spain",
    code: "ES",
    flag: "🇪🇸",
    continent: "Europe",
    capital: "Madrid",
    description:
      "Passionate culture, flamenco, and stunning Mediterranean coastline",
    rating: 4.7,
    visitors: "83.7M",
    bestTime: "May-Jun, Sep-Oct",
    highlights: ["Sagrada Familia", "Alhambra", "Barcelona", "Seville"],
    iconicQuery: "Sagrada Familia Barcelona Spain",
    image:
      "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "24°C", condition: "Sunny", humidity: "60%" },
    tags: ["Culture", "Beaches", "Art", "Food"],
  },
  {
    id: 6,
    name: "Greece",
    code: "GR",
    flag: "🇬🇷",
    continent: "Europe",
    capital: "Athens",
    description:
      "Birthplace of democracy with ancient ruins and beautiful islands",
    rating: 4.6,
    visitors: "33.0M",
    bestTime: "Apr-Jun, Sep-Oct",
    highlights: ["Parthenon", "Santorini", "Mykonos", "Delphi"],
    iconicQuery: "Parthenon Acropolis Athens Greece",
    image:
      "https://images.unsplash.com/photo-1555993539-1732b0258696?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "26°C", condition: "Sunny", humidity: "65%" },
    tags: ["History", "Islands", "Ancient", "Mediterranean"],
  },
  {
    id: 7,
    name: "Turkey",
    code: "TR",
    flag: "🇹🇷",
    continent: "Asia",
    capital: "Ankara",
    description: "Bridge between Europe and Asia with rich Ottoman heritage",
    rating: 4.5,
    visitors: "51.2M",
    bestTime: "Apr-May, Sep-Nov",
    highlights: ["Hagia Sophia", "Cappadocia", "Blue Mosque", "Pamukkale"],
    iconicQuery: "Hagia Sophia Istanbul Turkey",
    image:
      "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "23°C", condition: "Mild", humidity: "70%" },
    tags: ["History", "Culture", "Architecture", "Hot Air Balloons"],
  },
  {
    id: 8,
    name: "Thailand",
    code: "TH",
    flag: "🇹🇭",
    continent: "Asia",
    capital: "Bangkok",
    description: "Tropical paradise with rich culture and stunning beaches",
    rating: 4.6,
    visitors: "39.8M",
    bestTime: "Nov-Mar",
    highlights: ["Bangkok", "Phuket", "Chiang Mai", "Temples"],
    iconicQuery: "Wat Arun temple Bangkok Thailand",
    image:
      "https://images.unsplash.com/photo-1563492065-bf4e0bb2ba7e?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "32°C", condition: "Tropical", humidity: "80%" },
    tags: ["Beaches", "Culture", "Food", "Temples"],
  },
  {
    id: 9,
    name: "India",
    code: "IN",
    flag: "🇮🇳",
    continent: "Asia",
    capital: "New Delhi",
    description:
      "Diverse land of spirituality, spices, and incredible monuments",
    rating: 4.4,
    visitors: "17.9M",
    bestTime: "Oct-Mar",
    highlights: ["Taj Mahal", "Golden Temple", "Kerala", "Rajasthan"],
    iconicQuery: "Taj Mahal Agra India",
    image:
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "28°C", condition: "Hot", humidity: "75%" },
    tags: ["Spirituality", "History", "Spices", "Culture"],
  },
  {
    id: 10,
    name: "China",
    code: "CN",
    flag: "🇨🇳",
    continent: "Asia",
    capital: "Beijing",
    description: "Ancient civilization with modern marvels and rich traditions",
    rating: 4.5,
    visitors: "65.7M",
    bestTime: "Apr-May, Sep-Oct",
    highlights: ["Great Wall", "Forbidden City", "Terracotta Army", "Shanghai"],
    iconicQuery: "Great Wall of China Beijing",
    image:
      "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "18°C", condition: "Variable", humidity: "68%" },
    tags: ["History", "Culture", "Modern", "Ancient"],
  },
  {
    id: 11,
    name: "Egypt",
    code: "EG",
    flag: "🇪🇬",
    continent: "Africa",
    capital: "Cairo",
    description: "Ancient wonders and mysteries of the pharaohs",
    rating: 4.4,
    visitors: "13.1M",
    bestTime: "Oct-Apr",
    highlights: ["Pyramids", "Sphinx", "Nile River", "Valley of Kings"],
    iconicQuery: "Pyramids Giza Egypt sphinx",
    image:
      "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "25°C", condition: "Dry", humidity: "45%" },
    tags: ["History", "Ancient", "Desert", "Culture"],
  },
  {
    id: 12,
    name: "Morocco",
    code: "MA",
    flag: "🇲🇦",
    continent: "Africa",
    capital: "Rabat",
    description: "Exotic blend of Arab, Berber, and European cultures",
    rating: 4.3,
    visitors: "13.0M",
    bestTime: "Mar-May, Sep-Nov",
    highlights: ["Marrakech", "Casablanca", "Sahara", "Fes"],
    iconicQuery: "Hassan II Mosque Casablanca Morocco",
    image:
      "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "24°C", condition: "Dry", humidity: "55%" },
    tags: ["Desert", "Culture", "Markets", "Architecture"],
  },
  {
    id: 13,
    name: "South Africa",
    code: "ZA",
    flag: "🇿🇦",
    continent: "Africa",
    capital: "Cape Town",
    description: "Rainbow nation with diverse wildlife and stunning landscapes",
    rating: 4.5,
    visitors: "10.2M",
    bestTime: "May-Sep",
    highlights: [
      "Table Mountain",
      "Kruger Park",
      "Cape of Good Hope",
      "Johannesburg",
    ],
    iconicQuery: "Table Mountain Cape Town South Africa",
    image:
      "https://images.unsplash.com/photo-1484318571209-661cf29a69ea?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "20°C", condition: "Mild", humidity: "65%" },
    tags: ["Wildlife", "Nature", "Wine", "Adventure"],
  },
  {
    id: 14,
    name: "Kenya",
    code: "KE",
    flag: "🇰🇪",
    continent: "Africa",
    capital: "Nairobi",
    description: "Home to the Great Migration and incredible wildlife",
    rating: 4.4,
    visitors: "2.0M",
    bestTime: "Jun-Oct, Jan-Mar",
    highlights: ["Masai Mara", "Mount Kenya", "Amboseli", "Lamu"],
    iconicQuery: "Masai Mara safari Kenya wildebeest",
    image:
      "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "25°C", condition: "Savanna", humidity: "70%" },
    tags: ["Safari", "Wildlife", "Nature", "Adventure"],
  },
  {
    id: 15,
    name: "United States",
    code: "US",
    flag: "🇺🇸",
    continent: "North America",
    capital: "Washington DC",
    description: "Land of diversity from coast to coast with iconic landmarks",
    rating: 4.6,
    visitors: "79.3M",
    bestTime: "Apr-Jun, Sep-Nov",
    highlights: [
      "Statue of Liberty",
      "Grand Canyon",
      "Yellowstone",
      "Golden Gate",
    ],
    iconicQuery: "Statue of Liberty New York USA",
    image:
      "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "22°C", condition: "Variable", humidity: "65%" },
    tags: ["Diversity", "Nature", "Cities", "Culture"],
  },
  {
    id: 16,
    name: "Canada",
    code: "CA",
    flag: "🇨🇦",
    continent: "North America",
    capital: "Ottawa",
    description:
      "Vast wilderness, friendly people, and stunning natural beauty",
    rating: 4.7,
    visitors: "22.1M",
    bestTime: "May-Oct",
    highlights: ["Niagara Falls", "Banff", "CN Tower", "Quebec City"],
    iconicQuery: "Niagara Falls Canada",
    image:
      "https://images.unsplash.com/photo-1503614472-8c93d56cd72b?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "15°C", condition: "Cool", humidity: "60%" },
    tags: ["Nature", "Wilderness", "Friendly", "Clean"],
  },
  {
    id: 17,
    name: "Mexico",
    code: "MX",
    flag: "🇲🇽",
    continent: "North America",
    capital: "Mexico City",
    description: "Rich Mayan heritage, vibrant culture, and beautiful beaches",
    rating: 4.4,
    visitors: "45.0M",
    bestTime: "Dec-Apr",
    highlights: ["Chichen Itza", "Cancun", "Mexico City", "Tulum"],
    iconicQuery: "Chichen Itza pyramid Mexico",
    image:
      "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "26°C", condition: "Warm", humidity: "70%" },
    tags: ["Mayan", "Beaches", "Culture", "Food"],
  },
  {
    id: 18,
    name: "Brazil",
    code: "BR",
    flag: "🇧🇷",
    continent: "South America",
    capital: "Brasília",
    description: "Vibrant culture, carnival spirit, and Amazon rainforest",
    rating: 4.5,
    visitors: "6.6M",
    bestTime: "Apr-Sep",
    highlights: ["Rio de Janeiro", "Amazon", "Iguazu Falls", "Carnival"],
    iconicQuery: "Christ the Redeemer Rio de Janeiro Brazil",
    image:
      "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "28°C", condition: "Tropical", humidity: "85%" },
    tags: ["Carnival", "Rainforest", "Beaches", "Culture"],
  },
  {
    id: 19,
    name: "Argentina",
    code: "AR",
    flag: "🇦🇷",
    continent: "South America",
    capital: "Buenos Aires",
    description:
      "Land of tango, wine, and dramatic landscapes from pampas to glaciers",
    rating: 4.5,
    visitors: "7.4M",
    bestTime: "Mar-May, Sep-Nov",
    highlights: ["Buenos Aires", "Iguazu Falls", "Patagonia", "Mendoza"],
    iconicQuery: "Perito Moreno glacier Argentina Patagonia",
    image:
      "https://images.unsplash.com/photo-1544737151681-6e4992999de1?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "18°C", condition: "Temperate", humidity: "65%" },
    tags: ["Tango", "Wine", "Glaciers", "Culture"],
  },
  {
    id: 20,
    name: "Peru",
    code: "PE",
    flag: "🇵🇪",
    continent: "South America",
    capital: "Lima",
    description: "Ancient Incan heritage and dramatic Andean landscapes",
    rating: 4.6,
    visitors: "4.4M",
    bestTime: "May-Sep",
    highlights: ["Machu Picchu", "Cusco", "Sacred Valley", "Amazon"],
    iconicQuery: "Machu Picchu Peru Inca ruins",
    image:
      "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "19°C", condition: "Mountain", humidity: "55%" },
    tags: ["History", "Mountains", "Culture", "Adventure"],
  },
  {
    id: 21,
    name: "Chile",
    code: "CL",
    flag: "🇨🇱",
    continent: "South America",
    capital: "Santiago",
    description:
      "Long narrow country with diverse geography from desert to glaciers",
    rating: 4.4,
    visitors: "5.7M",
    bestTime: "Dec-Mar, Sep-Nov",
    highlights: [
      "Atacama Desert",
      "Easter Island",
      "Torres del Paine",
      "Santiago",
    ],
    iconicQuery: "Easter Island moai statues Chile",
    image:
      "https://images.unsplash.com/photo-1544737150-6f4d999988c6?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "20°C", condition: "Mediterranean", humidity: "60%" },
    tags: ["Desert", "Islands", "Wine", "Nature"],
  },
  {
    id: 22,
    name: "Australia",
    code: "AU",
    flag: "🇦🇺",
    continent: "Oceania",
    capital: "Canberra",
    description: "Diverse landscapes from outback to coral reefs",
    rating: 4.7,
    visitors: "9.5M",
    bestTime: "Sep-Nov, Mar-May",
    highlights: [
      "Sydney Opera House",
      "Great Barrier Reef",
      "Uluru",
      "Melbourne",
    ],
    iconicQuery: "Sydney Opera House Australia harbour",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "24°C", condition: "Sunny", humidity: "60%" },
    tags: ["Reef", "Wildlife", "Cities", "Outback"],
  },
  {
    id: 23,
    name: "New Zealand",
    code: "NZ",
    flag: "🇳🇿",
    continent: "Oceania",
    capital: "Wellington",
    description:
      "Adventure capital with breathtaking landscapes and Maori culture",
    rating: 4.9,
    visitors: "3.9M",
    bestTime: "Dec-Mar, Sep-Nov",
    highlights: ["Queenstown", "Milford Sound", "Hobbiton", "Abel Tasman"],
    iconicQuery: "Milford Sound fiordland New Zealand",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "20°C", condition: "Mild", humidity: "65%" },
    tags: ["Adventure", "Nature", "Culture", "Filming Locations"],
  },
  {
    id: 24,
    name: "Norway",
    code: "NO",
    flag: "🇳🇴",
    continent: "Europe",
    capital: "Oslo",
    description:
      "Spectacular fjords and natural beauty in the land of the midnight sun",
    rating: 4.8,
    visitors: "6.1M",
    bestTime: "May-Sep",
    highlights: ["Fjords", "Bergen", "Lofoten", "Midnight Sun"],
    iconicQuery: "Geirangerfjord Norway fjords",
    image:
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "15°C", condition: "Cool", humidity: "70%" },
    tags: ["Fjords", "Nature", "Adventure", "Midnight Sun"],
  },
  {
    id: 25,
    name: "Sweden",
    code: "SE",
    flag: "🇸🇪",
    continent: "Europe",
    capital: "Stockholm",
    description: "Land of ABBA, IKEA, and stunning archipelagos",
    rating: 4.6,
    visitors: "7.7M",
    bestTime: "May-Sep",
    highlights: ["Stockholm", "Gothenburg", "Lapland", "Archipelago"],
    iconicQuery: "Stockholm archipelago Sweden colorful houses",
    image:
      "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "16°C", condition: "Cool", humidity: "68%" },
    tags: ["Archipelago", "Design", "Nature", "Northern Lights"],
  },
  {
    id: 26,
    name: "Netherlands",
    code: "NL",
    flag: "🇳🇱",
    continent: "Europe",
    capital: "Amsterdam",
    description: "Land of tulips, windmills, and charming canals",
    rating: 4.5,
    visitors: "20.1M",
    bestTime: "Apr-May, Sep-Oct",
    highlights: ["Amsterdam", "Keukenhof", "Kinderdijk", "Utrecht"],
    iconicQuery: "Kinderdijk windmills Netherlands tulips",
    image:
      "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "17°C", condition: "Mild", humidity: "75%" },
    tags: ["Windmills", "Tulips", "Canals", "Cycling"],
  },
  {
    id: 27,
    name: "Germany",
    code: "DE",
    flag: "🇩🇪",
    continent: "Europe",
    capital: "Berlin",
    description: "Rich history, fairy tale castles, and Oktoberfest",
    rating: 4.5,
    visitors: "39.6M",
    bestTime: "May-Sep",
    highlights: ["Neuschwanstein", "Berlin Wall", "Munich", "Rhine Valley"],
    iconicQuery: "Neuschwanstein castle Bavaria Germany",
    image:
      "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "18°C", condition: "Temperate", humidity: "70%" },
    tags: ["Castles", "History", "Beer", "Culture"],
  },
  {
    id: 28,
    name: "United Kingdom",
    code: "GB",
    flag: "🇬🇧",
    continent: "Europe",
    capital: "London",
    description: "Monarchy, tea culture, and rich literary heritage",
    rating: 4.4,
    visitors: "40.9M",
    bestTime: "May-Sep",
    highlights: ["Big Ben", "Stonehenge", "Edinburgh", "Lake District"],
    iconicQuery: "Big Ben London UK Parliament",
    image:
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "15°C", condition: "Cloudy", humidity: "78%" },
    tags: ["History", "Royal", "Literature", "Countryside"],
  },
  {
    id: 29,
    name: "Russia",
    code: "RU",
    flag: "🇷🇺",
    continent: "Asia",
    capital: "Moscow",
    description:
      "Vast country spanning 11 time zones with rich cultural heritage",
    rating: 4.3,
    visitors: "24.4M",
    bestTime: "May-Sep",
    highlights: ["Red Square", "Hermitage", "Trans-Siberian", "St. Petersburg"],
    iconicQuery: "Red Square Moscow Kremlin Russia",
    image:
      "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "12°C", condition: "Cold", humidity: "65%" },
    tags: ["History", "Architecture", "Culture", "Vast"],
  },
  {
    id: 30,
    name: "South Korea",
    code: "KR",
    flag: "🇰🇷",
    continent: "Asia",
    capital: "Seoul",
    description: "K-pop culture, advanced technology, and delicious cuisine",
    rating: 4.6,
    visitors: "17.5M",
    bestTime: "Apr-Jun, Sep-Nov",
    highlights: ["Gyeongbokgung", "Busan", "Jeju Island", "DMZ"],
    iconicQuery: "Gyeongbokgung palace Seoul South Korea",
    image:
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "19°C", condition: "Temperate", humidity: "68%" },
    tags: ["K-pop", "Technology", "Food", "Culture"],
  },
  {
    id: 31,
    name: "Indonesia",
    code: "ID",
    flag: "🇮🇩",
    continent: "Asia",
    capital: "Jakarta",
    description: "Archipelago of over 17,000 islands with diverse cultures",
    rating: 4.4,
    visitors: "15.8M",
    bestTime: "Apr-Oct",
    highlights: ["Bali", "Borobudur", "Komodo Island", "Jakarta"],
    iconicQuery: "Borobudur temple Java Indonesia",
    image:
      "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "30°C", condition: "Tropical", humidity: "85%" },
    tags: ["Islands", "Temples", "Beaches", "Culture"],
  },
  {
    id: 32,
    name: "Portugal",
    code: "PT",
    flag: "🇵🇹",
    continent: "Europe",
    capital: "Lisbon",
    description: "Charming coastal country with port wine and azulejo tiles",
    rating: 4.5,
    visitors: "24.6M",
    bestTime: "May-Sep",
    highlights: ["Porto", "Lisbon", "Algarve", "Sintra"],
    iconicQuery: "Pena Palace Sintra Portugal",
    image:
      "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "22°C", condition: "Sunny", humidity: "65%" },
    tags: ["Coastal", "Wine", "History", "Architecture"],
  },
  {
    id: 33,
    name: "Croatia",
    code: "HR",
    flag: "🇭🇷",
    continent: "Europe",
    capital: "Zagreb",
    description: "Stunning Adriatic coastline with medieval cities",
    rating: 4.6,
    visitors: "19.6M",
    bestTime: "May-Sep",
    highlights: ["Dubrovnik", "Plitvice Lakes", "Split", "Zagreb"],
    iconicQuery: "Dubrovnik old town Croatia",
    image:
      "https://images.unsplash.com/photo-1555993539-1732b0258696?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "25°C", condition: "Mediterranean", humidity: "68%" },
    tags: ["Coastline", "Medieval", "National Parks", "Islands"],
  },
  {
    id: 34,
    name: "Vietnam",
    code: "VN",
    flag: "🇻🇳",
    continent: "Asia",
    capital: "Hanoi",
    description:
      "Rich history, stunning landscapes, and incredible street food",
    rating: 4.5,
    visitors: "18.0M",
    bestTime: "Oct-Apr",
    highlights: ["Ha Long Bay", "Ho Chi Minh City", "Hoi An", "Hanoi"],
    iconicQuery: "Ha Long Bay Vietnam limestone karsts",
    image:
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "27°C", condition: "Tropical", humidity: "78%" },
    tags: ["History", "Food", "Beaches", "Culture"],
  },
  {
    id: 35,
    name: "Jordan",
    code: "JO",
    flag: "🇯🇴",
    continent: "Asia",
    capital: "Amman",
    description: "Ancient rose-red city and desert landscapes",
    rating: 4.4,
    visitors: "5.3M",
    bestTime: "Mar-May, Sep-Nov",
    highlights: ["Petra", "Wadi Rum", "Dead Sea", "Jerash"],
    iconicQuery: "Petra treasury Jordan rose city",
    image:
      "https://images.unsplash.com/photo-1544948503-4ad8d34d8e41?w=800&h=600&fit=crop&crop=center&auto=format&q=80",
    weather: { temp: "24°C", condition: "Arid", humidity: "50%" },
    tags: ["Ancient", "Desert", "History", "Adventure"],
  },
];

// Generate mock weather data
export const generateWeatherData = (_country) => {
  const weatherConditions = [
    "Sunny",
    "Partly Cloudy",
    "Cloudy",
    "Clear",
    "Tropical",
    "Cool",
    "Mountain",
    "Dry",
    "Hot",
    "Mild",
    "Variable",
    "Temperate",
    "Mediterranean",
    "Arid",
    "Savanna",
  ];
  const temps = [
    "8°C",
    "12°C",
    "15°C",
    "18°C",
    "19°C",
    "20°C",
    "22°C",
    "24°C",
    "25°C",
    "26°C",
    "27°C",
    "28°C",
    "30°C",
    "32°C",
  ];
  const humidity = [
    "45%",
    "50%",
    "55%",
    "60%",
    "65%",
    "68%",
    "70%",
    "75%",
    "78%",
    "80%",
    "85%",
  ];

  return {
    temp: temps[Math.floor(Math.random() * temps.length)],
    condition:
      weatherConditions[Math.floor(Math.random() * weatherConditions.length)],
    humidity: humidity[Math.floor(Math.random() * humidity.length)],
  };
};

// Generate mock reviews
export const generateReviews = (_country) => {
  const reviewTemplates = [
    {
      text: "Absolutely stunning destination! The culture and people are amazing.",
      rating: 5,
      author: "Sarah M.",
    },
    {
      text: "One of the most beautiful places I've ever visited. Highly recommended!",
      rating: 5,
      author: "Mike R.",
    },
    {
      text: "Great experience overall, would love to go back again soon.",
      rating: 4,
      author: "Emma L.",
    },
    {
      text: "Perfect for adventure seekers and culture enthusiasts alike.",
      rating: 5,
      author: "Alex K.",
    },
    {
      text: "Incredible landscapes and unforgettable memories made here.",
      rating: 5,
      author: "Lisa P.",
    },
    {
      text: "Amazing food, friendly locals, and breathtaking scenery.",
      rating: 4,
      author: "David C.",
    },
  ];
  return reviewTemplates.slice(0, Math.floor(Math.random() * 4) + 2);
};

// Get country by ID
export const getCountryById = (id) => {
  return countries.find((country) => country.id === parseInt(id));
};

// Search countries by name
export const searchCountries = (query) => {
  if (!query) return countries;
  return countries.filter(
    (country) =>
      country.name.toLowerCase().includes(query.toLowerCase()) ||
      country.continent.toLowerCase().includes(query.toLowerCase()) ||
      country.tags.some((tag) =>
        tag.toLowerCase().includes(query.toLowerCase())
      )
  );
};

// Get countries by continent
export const getCountriesByContinent = (continent) => {
  if (!continent || continent === "All") return countries;
  return countries.filter((country) => country.continent === continent);
};

// Get top rated countries
export const getTopRatedCountries = (limit = 5) => {
  return countries.sort((a, b) => b.rating - a.rating).slice(0, limit);
};

export default {
  countries,
  generateWeatherData,
  generateReviews,
  getCountryById,
  searchCountries,
  getCountriesByContinent,
  getTopRatedCountries,
};
